<?php

/**
 * @file
 * The install file for cumulus.module
 */

/**
 * Implementation of hook_install().
 */
function cumulus_install() {
  drupal_install_schema('cumulus');
}

/**
 * Implementation of hook_schema().
 */
function cumulus_schema() {
  return array();
}

/**
 * Implementation of hook_uninstall().
 */
function cumulus_uninstall() {
  drupal_uninstall_schema('cumulus');
  db_query("DELETE FROM {variable} WHERE name LIKE 'cumulus_%'");
}

