<?php

/**
 * @file
 * The brain of Cumulus.
 *
 * Provides a Flash-based 3D tag cloud.
 * Based on WP-Cumulus for WordPress, by Roy Tanck.
 */

/**
 * Implements hook_enable().
 */
function cumulus_enable() {
  drupal_set_message(t('Cumulus has now been enabled. You need to !add a view with cumulus selected as output style to display the cloud. Or !activate the example view for a taxonomy cumulus block.', array('!add' => l(t('add'), 'admin/build/views/add'), '!activate' => l(t('activate'), 'admin/build/views'))));
  if (!module_exists('views_ui')) {
    drupal_set_message('If you need to activate the cumulus views make sure views UI is active as well.');
  }
}

/**
 * Implements hook_views_api().
 * Notifies the Views module that we're compatible with a particular API revision.
 */
function cumulus_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'cumulus') . '/includes/views',
  );
}

/**
 * Template function for cumulus style plugin.
 *
 * @param array $vars
 *  Array of template variables.
 */
function template_preprocess_views_view_cumulus(&$vars) {
  dpm($vars['view']->style_plugin->rendered_fields);
}

/**
 * Implements hook_help().
 */
function cumulus_help($path, $arg) {
  switch ($path) {
    case 'admin/help#cumulus':
      $output = '<p>' . t('Cumulus allows you to display strings like taxonomy\'s terms using a Flash movie that rotates them in 3D. This way, you can set it up like a 3D tag cloud. It works just like a regular tag cloud, but is more visually exciting!') . '</p>';
      return $output;
  }
}

function cumulus_views_options() {
  return array(
    'unique_id' => array('default' => ''),
    'title_field' => array('default' => ''),
    'link_field' => array('default' => ''),
    'use_field_as_weight' => array(
      'weight_text' => array('default' => 0),
      'weight_field' => array('default' => ''),
    ),
    'size_interval' => array('default' => 6),
    'flash_width' => array('default' => 200),
    'flash_height' => array('default' => 150),
    'flash_background' => array('default' => 'ffffff'),
    'flash_transparency' => array('default' => 'false'),
    'flash_color' => array('default' => 'ff0000'),
    'flash_color2' => array('default' => '000000'),
    'flash_hicolor' => array('default' => '666666'),
    'flash_speed' => array('default' => 100),
    'flash_distribute' => array('default' => 'true'),
    'flash_font_size' => array('default' => 10),
    'flash_font_size_interval' => array('default' => 2),
  );
    ),
  );
  );
}
